### ISSUE TITLE
Document the details of rules used by Package Validator

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/docs#489]
## What New Or Updated Would You Like To See?

Include details about each rule we currently run through using the Package Validator.
Without details about the rule itself, there can be times when a user is unable to update according to what the Validator flags.

## Why Is It Needed?

Quite a few of the rules that we have documented on https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/ are just stubs of the rules that we have. Without any details about what the rule is for and/or suggestions about how a user can fix the rule.

## Additional Context?

Additional tasks with separate issues
```[tasklist]
### Tasks
- [ ] https://github.com/chocolatey/docs/issues/504
- [ ] https://github.com/chocolatey/docs/issues/505
- [ ] https://github.com/chocolatey/docs/issues/510
```
