### ISSUE TITLE
Documentation Updates for Chocolatey Central Management 0.12.0

### ISSUE THREAD

**Issue by st3phhays** [chocolatey/docs#862]
## What New Or Updated Would You Like To See?

This is a common issue to attribute to documentation updates relating to Chocolatey Central Management 0.12.0

## Why Is It Needed?

We need to gather all of these PRs into one issue that is easy to find.

## Additional Context?

n/a

```[tasklist]
### Tasks
- [x] Add FAQ entry for Timezones, and which Windows Updates are required to get certain TimeZones, 5012170 - Adds in Qyzlorda, 5031362 - Adds in Yukon and South Sudan. (@corbob)
- [x] Add Documentation for Chocolatey Central Management > Usage > Website > Dashboard (@gep13)
- [x] Add Documentation for Chocolatey Central Management > Usage > Website > Reports (@vexx32)
- [x] Add Documentation for Chocolatey Central Management > Usage > Website > Administration > Users {@gep13)
- [x] Add Documentation for Chocolatey Central Management > Usage > Website > Administration > Audit Logs (@gep13)
- [x] Add Documentation for Chocolatey Central Management > Usage > Website > Administration > Maintenance (@gep13)
- [x] Add Documentation for Chocolatey Central Management > Usage > Website > Administration >Settings > General (@corbob)
```
